# Generated by Django 3.1 on 2020-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='editor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='writer',
            field=models.CharField(max_length=100),
        ),
    ]
