# Generated by Django 3.1.1 on 2020-09-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='grade',
        ),
    ]
