# Generated by Django 3.1.1 on 2020-10-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201008_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='averageGrade',
            new_name='average',
        ),
    ]
