# Generated by Django 3.1.1 on 2020-10-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201009_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='average',
            new_name='grade',
        ),
    ]
